spring.profiles.active=dev

spring.application.name=schoolapp
server.servlet.context-path=/schoolapp

spring.jpa.hibernate.ddl-auto=validate

#το default είναι true
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration

# το session κλείνει αυτόματα όταν επιστρέψει το service
# αν ήταν true, τότε το session θα παραμείνει ανοιχτό και θα μπορούμε να κάνουμε lazy loading
# (n + 1 queries) όμως πέφτει το performance (κάτι που δεν θέλουμε).
# Best practice είναι να κλείνει το session όταν επιστρέψει το service (false)
# να θυμόμαστε JOIN FETCH ή EntityGraph για να μην έχουμε lazy loading
spring.jpa.open-in-view=false
